In [135]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [136]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [137]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [138]:
data.corr('spearman') #

f1        f2        f3         y
f1  1.000000  0.050487  0.124497  0.069456
f2  0.050487  1.000000 -0.065721 -0.046593
f3  0.124497 -0.065721  1.000000  0.839882
y   0.069456 -0.046593  0.839882  1.000000

In [139]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [140]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

In [141]:
lr = SGDClassifier(loss="log_loss",eta0=0.001)
lr.fit(X,Y)
print(lr.coef_)

[[ 3093.6379758  36717.82791423 10273.28865933]]


In [142]:
svc = SGDClassifier(loss="hinge")
svc.fit(X,Y)
svc.coef_

array([[ 6781.51057688, -7428.02157651, 10850.06132892]])

* Standardization of data

In [143]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [144]:
svc = SGDClassifier(loss="hinge")
svc.fit(X,Y)
svc.coef_

array([[-4.02664119,  0.83142399, 16.08706248]])

In [145]:
lr = SGDClassifier(loss="log_loss")
lr.fit(X,Y)
lr.coef_

array([[-1.23118054, -2.03586002, 14.00677188]])